name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please search existing issues first.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the problem this feature would solve
      placeholder: e.g., Support ENS wildcard records in address bar
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? What problem does it address?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe how you’d like this feature to work
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots
